# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          younari.swift
paginate:       50
baseurl:        ""
url:            "https://younari.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         younari
  url:          https://younari.github.io/
  email:        younari.me@icloud.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/younari/younari.github.io

# Gems
gems:
  - jekyll-paginate
