# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          amy.swift
paginate:       100
baseurl:        "https://amywork.github.io"
url:            "https://amywork.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         amy
  url:          https://amywork.github.io
  email:        younari.me@icloud.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/amywork/amywork.github.io

# Gems
gems:
  - jekyll-paginate
